name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_REGION }}  # AWS 리전을 변수화
        role-to-assume: ${{ secrets.ARN_ECR_PUSH_ROLE }}  # AWS IAM 역할을 변수화
        role-session-name: ecrPrivatePushRole

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Set IMAGE_TAG
      run: |
        echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
        echo "ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}" >> $GITHUB_ENV  # ECR 리포지토리를 변수화
        echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and push Docker image to Amazon ECR
      run: |
        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Clone and update manifest repository
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        git clone https://${{ secrets.PAT_TOKEN }}@github.com/${{ secrets.MANIFEST_REPO }}.git  # manifest 리포지토리 URL을 변수화
        cd manifest
        sed -i "s|image: .*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}|" k8s/deploy-basic2.yml
        git config --global user.email "${{ secrets.GIT_EMAIL }}"  # Git 사용자 이메일을 변수화
        git config --global user.name "${{ secrets.GIT_NAME }}"  # Git 사용자 이름을 변수화
        if [ -n "$(git status --porcelain)" ]; then
          git add k8s/deploy-basic2.yml
          git commit -m "Update image to $IMAGE_TAG"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ secrets.MANIFEST_REPO }}.git main
        else
          echo "No changes to commit"
        fi
